// Generated by https://quicktype.io

export interface Medicos {
  _id:      string;
  name:     string;
  user:     MedicoUser;
  hospital: MedicoHospital;
  __v:      number;
  img:      string;
  isActive: boolean;
}

export interface MedicoHospital {
  _id:  string;
  name: string;
}

export interface MedicoUser {
  _id:  string;
  name: string;
  img:  string;
}

export interface MedicosResp{
  total: number;
  medicos: Medicos[];
}
